export const HANDLE_LOADING = "HANDLE_LOADING";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const HANDLE_EMAIL = "HANDLE_EMAIL";
export const STORE_USER_DATA = "STORE_USER_DATA";
export const STORE_USER_EMAILS = "STORE_USER_EMAILS";